### ISSUE TITLE
train.py requires best_decoder.pth that is missing.

### ISSUE THREAD

**Issue by santaklouse** [mzbac/image2dsl#1]
Hi, I have an error:
```
python3.9 ./train.py
Some weights of ViTModel were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized: ['vit.pooler.dense.bias', 'vit.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/Users/alexnevpryaga/projects/santaklouse/image2dsl/./train.py", line 102, in <module>
    decoder.load_state_dict(torch.load("best_decoder.pth"))
  File "/opt/homebrew/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/homebrew/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/homebrew/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'best_decoder.pth'
```

**Comment by Ravishukla1234** [comment]
I commented the line 102, i.e.,
decoder.load_state_dict(torch.load("best_decoder.pth"))

And was able to do the training successfully

**Comment by mzbac** [comment]
Yeah, it's just a saved checkpoint. If you don't have it, please comment it out.
